[package]
name = "dust-lpc11xx"
version = "0.1.0"
authors = ["Juergen Stuber <juergen@jstuber.net>"]

[profile.dev]
lto = true

[profile.release]
lto = true

[features]
lpc1114 = ["lpc11xx"]

lpc11xx = []
[dependencies]
volatile-register = "0.2.0"
