# array_layout = "Visual"
array_layout = "Block"
# array_width = 60
# chain_indent = "Block"
# chain_one_line_max = 60
# closure_block_indent_threshold = 7
closure_block_indent_threshold = 1
# comment_width = 80
# condense_wildcard_suffices = false
condense_wildcard_suffices = true
# control_brace_style = "AlwaysSameLine"
control_brace_style = "ClosingNextLine"
# disable_all_formatting = false
# error_on_line_overflow = true
# fn_args_density = "Tall"
# fn_args_layout = "Visual"
fn_args_layout = "Block"
# fn_args_paren_newline = true
fn_args_paren_newline = false
# fn_brace_style = "SameLineWhere"
# fn_call_style = "Visual"
fn_call_style = "Block"
# fn_call_width = 60
# fn_empty_single_line = true
# fn_return_indent = "WithArgs"
# fn_single_line = false
# force_explicit_abi = true
# force_format_strings = false
# format_strings = true
# generics_indent = "Visual"
generics_indent = "Block"
# hard_tabs = false
# impl_empty_single_line = true
# indent_match_arms = true
# item_brace_style = "SameLineWhere"
# match_block_trailing_comma = false
match_block_trailing_comma = true
# max_width = 100
max_width = 80
# newline_style = "Unix"
# normalize_comments = false
normalize_comments = true
# reorder_imported_names = false
reorder_imported_names = true
# reorder_imports = false
reorder_imports = true
# single_line_if_else_max_width = 50
# skip_children = false
# space_after_bound_colon = true
# space_after_type_annotation_colon = true
# space_before_bound = false
# space_before_type_annotation = false
# spaces_around_ranges = false
spaces_around_ranges = true
# spaces_within_angle_brackets = false
# spaces_within_parens = false
# spaces_within_square_brackets = false
# struct_lit_multiline_style = "PreferSingle"
# struct_lit_style = "Visual"
struct_lit_style = "Block"
# struct_lit_width = 18
# struct_variant_width = 35
# tab_spaces = 4
# take_source_hints = false
# trailing_comma = "Vertical"
# type_punctuation_density = "Wide"
# use_try_shorthand = false
use_try_shorthand = true
# where_density = "CompressedIfEmpty"
where_density = "Vertical"
# where_layout = "Vertical"
# where_pred_indent = "Visual"
where_pred_indent = "Block"
# where_style = "Default"
where_style = "Rfc"
# wrap_comments = false
wrap_comments = true
# wrap_match_arms = true
# write_mode = "Replace"
