[package]
edition = "2021"
name = "dust-runtime"
version = "0.1.0"
authors = ["Juergen Stuber <juergen@jstuber.net>"]
description = "Rust language runtime."
license = "MIT OR Apache-2.0"

[dependencies]
dust-panic = { path = "../dust-panic", version = "0.1.0" }
