[package]
edition = "2021"
name = "dust-register"
version = "0.1.0"
authors = ["Juergen Stuber <juergen@jstuber.net>"]
description = "Volatile access to hardware registers based on pointers"

[dependencies]
